feat: add borders
wlrfx/scenefx pull request #23
Opened 2023-10-19 06:09 UTC by WillPower3309

TODO:

+ [] border setting
+ [] add border width to corner radius
+ [] border stencil

2023-10-19 06:12 UTC, WillPower3309 commented
will fix `meson.build` next commit

2023-10-20 06:19 UTC, WillPower3309 commented
Need to fix a weird bug, corners of the borders don't round, and the stencil cuts out the window surface texture as well as the border area

2023-10-20 07:23 UTC, ErikReider requested changes

2023-10-20 07:23 UTC, ErikReider commented on render/fx_renderer/fx_renderer.c
> +		fx_renderer_stencil_mask_close(false);
Don't forget to call the stencil fini function when done

2023-10-20 07:23 UTC, ErikReider commented on types/scene/wlr_scene.c
> +		wlr_region_expand(&node->visible, &node->visible, buffer->border_size);
Maybe check if the size is larger than 0?

2023-10-20 07:23 UTC, ErikReider commented on types/scene/wlr_scene.c
> +		int size, float color[static 4], int corner_radius) {
What about passing the scene_buffer pointer instead of these three parameters?

2023-10-20 11:13 UTC, ErikReider commented
What about moving this into a sister-node to our `wlr_scene_buffer` as a new node type? We could provide shadow control, border x/y offset, width, height, etc without messing with the `wlr_scene_buffer` struct as intended by the wlroots devs:

![image](https://github.com/wlrfx/scenefx/assets/35975961/879cfa22-49f3-4506-87f0-4d2dd0d84100)

But then again, we could just add those variables to the `wlr_scene_buffer` struct and get the same result

2023-10-20 14:45 UTC, WillPower3309 commented
> What about moving this into a sister-node to our `wlr_scene_buffer` as a new node type? We could provide shadow control, border x/y offset, width, height, etc without messing with the `wlr_scene_buffer` struct as intended by the wlroots devs:
> 
> ![image](https://github.com/wlrfx/scenefx/assets/35975961/879cfa22-49f3-4506-87f0-4d2dd0d84100)
> 
> This would allow the comp to add multiple borders as discussed earlier.
> 
> But then again, we could just add those variables to the `wlr_scene_buffer` struct and get the same result

Thanks for closing out this couple of items I had to do, I agree. I was actually going to suggest something similar, partly since shadows also depend on border values

2023-10-26 05:03 UTC, WillPower3309 commented
Just need to fix a corner issue and close out the scaling / rotation and this is done!

2023-10-26 05:04 UTC, WillPower3309 commented
I'll try to close out the last bit tomorrow

2023-11-01 06:15 UTC, WillPower3309 commented
![2023-11-01_01-11-1698815715](https://github.com/wlrfx/scenefx/assets/13266308/f3dbc7c8-09bc-4a85-b976-828c5b726a74)
Still a bit of corner cropping, almost seems like the stencil is also applying to the surface texture

2023-11-02 06:04 UTC, WillPower3309 commented
Might rename the function to render_rect_around_rect, to make it less specific to borders, as compositors should be able to use it for titlebars too

2024-09-11 16:35 UTC, closed without merging