feat: add corner radius and window wrapping to rect_nodes
wlrfx/scenefx pull request #69
Opened 2024-10-26 04:13 UTC by WillPower3309

2024-10-26 04:14 UTC, WillPower3309 commented
For some reason the example isn't rounding its outer corners, will take a look tomorrow

2024-10-26 09:51 UTC, ErikReider requested changes

2024-10-26 09:51 UTC, ErikReider commented on include/scenefx/types/wlr_scene.h
> + * change the width and height of an existing rectangle node.
Intended change?

2024-10-26 09:51 UTC, ErikReider commented on render/fx_renderer/fx_pass.c
> +			window_box.width - window_corner_radius * 0.6, window_box.height - window_corner_radius * 0.6);
Make sure that the width and height aren't 0

2024-10-26 09:51 UTC, ErikReider commented on render/fx_renderer/fx_pass.c
> +			window_box.width - window_corner_radius * 0.6, window_box.height - window_corner_radius * 0.6);
Might as well change this here instead of my PR

2024-10-26 09:51 UTC, ErikReider commented on tinywl/tinywl.c
> +	wlr_scene_node_destroy(&toplevel->shadow->node);
Isn't needed. Automatically called when its parent is destroyed, the line below :)

2024-10-26 09:51 UTC, ErikReider commented on types/scene/wlr_scene.c
> +			fx_render_pass_add_rounded_rect(data->render_pass, &rounded_rect_options);
Don't forget to break here

2024-10-29 05:51 UTC, WillPower3309 commented
Need to get window resizing working in tinywl again

2024-10-29 05:52 UTC, WillPower3309 commented
Will add window wrapping to other rect nodes as a follow-up

2024-10-29 23:43 UTC, merged